# Project variables
project_root: ~/projects/bmi5370/
output_root: results
input_root: input
build: hg19
conda: ~/miniconda

# WES variables
annovar_script: ~/projects/bmi5370/workflow/annovar/table_annovar.pl
human_db:  ~/projects/bmi5370/workflow/annovar/humandb/
dp_threshold: 500